### ISSUE TITLE
How to edit the settings of the job manager to do sequential submission of the job queue ?

### ISSUE THREAD

**Issue by bradraj** [abinit/abitutorials#3]
The abipy submits the job simultaneously and it crashes the system. When the next job input depends on the previous job then it is running sequencially. But when it is not dependent, all the jobs are submitted at once and when the RAM of the system overloads, it crashes the system.

Is there any way to submit the job using job scheduler sequencially one by one ???

**Comment by gmatteo** [comment]
Add the following options to scheduler.yml

```yml
# Limit on the number of jobs that can be present in the queue. (DEFAULT: 200)
max_njobs_inqueue: 2

# Maximum number of cores that can be used by the scheduler.
max_ncores_used: 4
```

To get the list of options supported in scheduler.yml and manager.yml, use:

```sh
abidoc.py scheduler
abidcoc.py manager
```
